.TH SN1FF_CLEANER 8
.SH NAME
sn1ff_cleaner \- daemon service run utility, to remove expired check results files
.SH SYNOPSIS
.B sn1ff_cleaner
[\fIOPTIONS\fR]
.SH DESCRIPTION
Run directly by the sn1ff_service to remove sn1ff check results files, that have exceeded their Time-to-Live (TTL) value. It is not meant typically to be run directly by the user.
.SH OPTIONS
.TP
.B \-h
Show available help information.
.SH FURTHER INFORMATION
For details of installation and example checks, see the sn1ff Github repository:
.PP
.B https://github.com/GwynDavies/sn1ff
.PP
.SH SEE ALSO
.SS Other related pages:
.BR sn1ff_service (8),
.BR sn1ff (7),
.BR sn1ff_monitor (1),
.BR sn1ff_client (1),
.BR sn1ff_license (1),
.BR sn1ff_conf (1).
.SH AUTHOR
Written by Gwyn Davies
.PP
.B https://github.com/GwynDavies/sn1ff
