.TH SN1FF_LICENSE 1 
.SH NAME
sn1ff_license \- display sn1ff license
.SH SYNOPSIS
.B sn1ff_license
.SH DESCRIPTION
sn1ff_license is a command-line program, that simply displays the sn1ff license.
.SH OPTIONS
.TP
.B There are no options
.SH EXAMPLE(S)

.nf
   sn1ff_license
.fi
.SH FURTHER INFORMATION
For details of installation and example checks, see the sn1ff Github repository:
.PP
.B https://github.com/GwynDavies/sn1ff
.PP
.SH SEE ALSO
.SS Other related pages on the sn1ff server:
.BR sn1ff_service (8),
.BR sn1ff_cleaner (8),
.BR sn1ff (7),
.BR sn1ff_monitor (1).
.SS Other related pages on sn1ff clients:
.BR sn1ff_client (1),
.BR sn1ff_conf (1).
.SH AUTHOR
Written by Gwyn Davies
.PP
.B https://github.com/GwynDavies/sn1ff
